spring.application.name=chatApplication

# Import the .env file from the project root or backend directory
spring.config.import=optional:file:.env[.properties],optional:file:Backend/.env[.properties]


# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
